#ifndef UNREMARKABLE_UTILITY_HPP
#define UNREMARKABLE_UTILITY_HPP

#define UNREMARKABLE_NAMESPACE_BEGIN namespace Unremarkable {
#define UNREMARKABLE_NAMESPACE_END }

#define UNREMARKABLE_PUBLIC_FUNCTIONS public:
#define UNREMARKABLE_PUBLIC_VARIABLES public:

#define UNREMARKABLE_PRIVATE_FUNCTIONS private:
#define UNREMARKABLE_PRIVATE_VARIABLES private:

#endif